---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-{{ cookiecutter.role_name }}"
      ansible.builtin.include_role:
        name: "ansible-role-{{ cookiecutter.role_name }}"
